import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import {
  Brain, ScanLine, Utensils, ChartBar, GraduationCap, ShieldAlert,
  MessageCircle, Sparkles, Mail, BookOpen, Activity,
} from "lucide-react";
import { Section } from "@/components/Section";
import { getPublicStats } from "@/lib/public-stats.functions";

export const Route = createFileRoute("/ai-operations")({
  head: () => ({
    meta: [
      { title: "How AI runs NutriSight — Live AI Operations" },
      { name: "description", content: "Transparency page: every AI agent in NutriSight, what it decides autonomously, what the human founder does, plus live counters of scans and Gemini calls." },
      { property: "og:title", content: "How AI runs NutriSight" },
      { property: "og:description", content: "Live transparency into the agents that power NutriSight — and what the human still owns." },
    ],
    links: [{ rel: "canonical", href: "https://nutrisight.lovable.app/ai-operations" }],
  }),
  component: AiOpsPage,
});

type AgentRow = {
  icon: typeof Brain;
  name: string;
  status: "Live" | "Beta" | "Planned";
  decides: string;
  human: string;
};

const productAgents: AgentRow[] = [
  { icon: ScanLine, name: "Food Recognition Agent", status: "Live", decides: "Identifies dishes, ingredients and portions from camera images using Google Gemini 2.5 Flash multimodal vision.", human: "Founder reviews edge-case misclassifications weekly to refine prompts." },
  { icon: Utensils, name: "Menu Understanding Agent", status: "Live", decides: "Reads café and restaurant menus from photos, picks the best dish for the user's goal.", human: "Founder curates representative menu test set for QA." },
  { icon: ChartBar, name: "Nutrition Estimation Agent", status: "Live", decides: "Estimates calories, sugar, carbs, protein, fiber and salt per serving via Gemini reasoning.", human: "Founder spot-checks against USDA / Frida database for calibration." },
  { icon: Sparkles, name: "Recommendation Agent", status: "Live", decides: "Generates a personalized recommendation based on the user's goal and the meal scanned.", human: "Founder writes goal taxonomy and safety guard prompts." },
  { icon: Brain, name: "Meal Memory Agent", status: "Live", decides: "Stores meals, computes daily totals, decides the next-best-action card on Today.", human: "Founder owns the daily target heuristics until learned per-user." },
  { icon: GraduationCap, name: "Coach & Learning Agent", status: "Live", decides: "Surfaces lessons matched to the user's current goal and recent scans.", human: "Founder approves new lesson content before publish." },
  { icon: ShieldAlert, name: "Safety Agent", status: "Live", decides: "Adds disclaimers, blocks medical-claim phrasing, refuses unsafe requests.", human: "Founder reviews flagged outputs weekly." },
];

const businessAgents: AgentRow[] = [
  { icon: MessageCircle, name: "Support Agent", status: "Beta", decides: "Drafts first-response replies to user emails and in-app feedback using Gemini, suggests resolutions.", human: "Founder reviews and sends every reply during beta." },
  { icon: Activity, name: "Onboarding Agent", status: "Beta", decides: "Personalizes a user's goal & starting lessons based on their signup answers.", human: "Founder owns the welcome email tone & cadence." },
  { icon: BookOpen, name: "Content Agent", status: "Planned", decides: "Will draft new Academy lessons weekly from a research outline and validate citations.", human: "Founder reviews and publishes — no auto-publish." },
  { icon: Mail, name: "Weekly Report Agent", status: "Planned", decides: "Will generate each Pro user's weekly nutrition report from their saved meals.", human: "Founder reviews the prompt and sample reports before rollout." },
];

function AiOpsPage() {
  const fetchStats = useServerFn(getPublicStats);
  const { data: stats } = useQuery({
    queryKey: ["public-stats"],
    queryFn: () => fetchStats(),
    refetchInterval: 30_000,
  });

  return (
    <>
      <section className="container-page pb-6 pt-16 text-center">
        <span className="inline-flex items-center gap-2 rounded-full border border-brand-blue/30 bg-brand-blue/10 px-3 py-1 text-xs font-semibold text-brand-blue-foreground">
          <Brain className="h-3.5 w-3.5" /> AI Operations · Live
        </span>
        <h1 className="mt-4 text-4xl font-extrabold md:text-5xl">How AI runs NutriSight</h1>
        <p className="mx-auto mt-3 max-w-2xl text-muted-foreground">
          Every prediction, recommendation and lesson on NutriSight is generated by an AI agent running
          in production today. This page lists those agents, what they decide on their own, and where the
          human founder is still in the loop.
        </p>
      </section>

      <Section eyebrow="Live counters" title="What the system has done so far">
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
          <Counter label="Users" value={stats?.users} />
          <Counter label="AI scans analyzed" value={stats?.scans} />
          <Counter label="Gemini calls logged" value={stats?.gemini_calls} />
          <Counter label="Lessons completed" value={stats?.lessons} />
          <Counter label="Beta signups" value={stats?.beta_signups} />
        </div>
        <p className="mt-4 text-center text-xs text-muted-foreground">
          Pulled live from the production database. Numbers are real, not simulated.
        </p>
      </Section>

      <Section eyebrow="Product agents" title="AI that runs the product">
        <AgentTable rows={productAgents} />
      </Section>

      <Section eyebrow="Business agents" title="AI that runs the company">
        <AgentTable rows={businessAgents} />
        <p className="mx-auto mt-6 max-w-2xl text-center text-sm text-muted-foreground">
          We label every agent honestly as <strong>Live</strong>, <strong>Beta</strong> or <strong>Planned</strong>.
          Nothing on this page is aspirational marketing.
        </p>
      </Section>

      <Section eyebrow="Stack" title="The Google Cloud stack behind NutriSight">
        <div className="mx-auto max-w-3xl rounded-3xl border border-border bg-card p-7 text-sm leading-relaxed text-muted-foreground">
          <p>
            <strong className="text-foreground">Google Gemini 2.5 Flash & 2.5 Pro</strong> — multimodal vision +
            reasoning for every food scan, menu read, recipe parse, comparison and meal description.
          </p>
          <p className="mt-3">
            <strong className="text-foreground">Lovable AI Gateway</strong> routes every Gemini call so we can
            log model, latency and outcome per request (visible to the founder in the Admin dashboard).
          </p>
          <p className="mt-3">
            <strong className="text-foreground">Lovable Cloud (managed Postgres + Auth + Storage)</strong> stores
            meal memory, learning progress, and scan events with row-level security per user.
          </p>
        </div>
      </Section>
    </>
  );
}

function Counter({ label, value }: { label: string; value: number | undefined }) {
  return (
    <div className="rounded-3xl border border-border bg-card p-6 text-center">
      <p className="font-display text-4xl font-extrabold">{value == null ? "—" : value.toLocaleString()}</p>
      <p className="mt-1 text-xs font-semibold uppercase tracking-wider text-muted-foreground">{label}</p>
    </div>
  );
}

function AgentTable({ rows }: { rows: AgentRow[] }) {
  return (
    <div className="overflow-hidden rounded-3xl border border-border bg-card">
      <table className="w-full text-sm">
        <thead>
          <tr className="border-b border-border bg-muted/40 text-left">
            <th className="p-4 font-semibold">Agent</th>
            <th className="p-4 font-semibold">Status</th>
            <th className="p-4 font-semibold">Decides autonomously</th>
            <th className="p-4 font-semibold">Human still owns</th>
          </tr>
        </thead>
        <tbody>
          {rows.map((r) => (
            <tr key={r.name} className="border-b border-border/60 last:border-0 align-top">
              <td className="p-4">
                <div className="flex items-center gap-2 font-semibold">
                  <r.icon className="h-4 w-4 text-primary" /> {r.name}
                </div>
              </td>
              <td className="p-4">
                <span className={
                  r.status === "Live"
                    ? "inline-flex rounded-full bg-success/15 px-2.5 py-0.5 text-[11px] font-bold text-success"
                    : r.status === "Beta"
                    ? "inline-flex rounded-full bg-warning/20 px-2.5 py-0.5 text-[11px] font-bold text-warning-foreground"
                    : "inline-flex rounded-full bg-muted px-2.5 py-0.5 text-[11px] font-bold text-muted-foreground"
                }>{r.status}</span>
              </td>
              <td className="p-4 text-muted-foreground">{r.decides}</td>
              <td className="p-4 text-muted-foreground">{r.human}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
