import { createFileRoute } from "@tanstack/react-router";
import { Section } from "@/components/Section";

export const Route = createFileRoute("/terms")({
  head: () => ({
    meta: [
      { title: "Terms of Service — NutriSight" },
      { name: "description", content: "The terms that govern your use of NutriSight, an AI nutrition assistant. Estimates only — not medical advice." },
      { property: "og:title", content: "NutriSight Terms of Service" },
      { property: "og:description", content: "Terms of use, disclaimers and acceptable use for NutriSight." },
    ],
    links: [{ rel: "canonical", href: "https://nutrisight.lovable.app/terms" }],
  }),
  component: TermsPage,
});

function TermsPage() {
  return (
    <Section eyebrow="Legal" title="Terms of Service">
      <div className="mx-auto max-w-3xl space-y-5 text-sm leading-relaxed text-muted-foreground">
        <p className="text-xs uppercase tracking-wider text-foreground/70">Last updated: June 2026</p>
        <p>By using NutriSight you agree to the following terms.</p>

        <h2 className="mt-6 text-lg font-bold text-foreground">1. The service</h2>
        <p>NutriSight is an AI-powered nutrition assistant. It uses Google Gemini to estimate the nutrition of food you scan, describe or compare. Outputs are <strong>estimates</strong>, generated by an AI model, and may be inaccurate.</p>

        <h2 className="mt-6 text-lg font-bold text-foreground">2. Not medical advice</h2>
        <p>NutriSight does <strong>not</strong> provide medical, nutritional or dietetic advice. Do not use it to diagnose, treat or manage any medical condition. If you have a health concern, consult a qualified professional.</p>

        <h2 className="mt-6 text-lg font-bold text-foreground">3. Account</h2>
        <p>You're responsible for the activity on your account and for keeping your sign-in secure. You may delete your account at any time from your profile.</p>

        <h2 className="mt-6 text-lg font-bold text-foreground">4. Acceptable use</h2>
        <ul className="list-inside list-disc space-y-1.5">
          <li>Don't upload images that aren't yours or that contain other people without consent.</li>
          <li>Don't attempt to reverse-engineer or abuse the API.</li>
          <li>Don't use NutriSight to encourage disordered eating.</li>
        </ul>

        <h2 className="mt-6 text-lg font-bold text-foreground">5. Paid plans</h2>
        <p>Pro plans are billed in EUR. You may cancel anytime; you keep access until the end of the paid period. Refund requests within 14 days of first purchase are honored under EU consumer law.</p>

        <h2 className="mt-6 text-lg font-bold text-foreground">6. Liability</h2>
        <p>To the maximum extent permitted by law, NutriSight is provided \"as is\" without warranty. We are not liable for decisions you make based on NutriSight estimates.</p>

        <h2 className="mt-6 text-lg font-bold text-foreground">7. Changes</h2>
        <p>We may update these terms. Material changes are communicated to active users by email at least 14 days in advance.</p>

        <p className="mt-8 text-xs">Contact: <a className="text-primary underline" href="mailto:hello@nutrisight.app">hello@nutrisight.app</a></p>
      </div>
    </Section>
  );
}
